@startuml
title Aktivitätsdiagramm – Gesamtprozess der Bücherkatalog-Anwendung

start

partition Benutzer {
  :Anwendung starten;
}

partition Benutzer {
  :Startbildschirm anzeigen;
  if (About anzeigen?) then (ja)
    :About anzeigen;
    :Zurück zum Startbildschirm;
    -> [Zurück zur Auswahl] 
    back to :Startbildschirm anzeigen;
  else (nein)
    :Buchsuche starten;
    :Suchbegriff eingeben;
  endif
}

partition System {
  :System durchsucht JSON-Datei;
  if (Suchergebnisse gefunden?) then (ja)
    :Trefferliste anzeigen;
  else (nein)
    :Meldung anzeigen: Keine Ergebnisse gefunden;
    stop
  endif
}

partition Benutzer {
  :Buch aus Trefferliste wählen;
}

partition System {
  :Buchdetails anzeigen;
  if (Rezensionen vorhanden?) then (ja)
    :Rezensionen anzeigen;
  else (nein)
    :Meldung anzeigen: Keine Rezensionen vorhanden;
  endif
  :Ähnliche Bücher ermitteln;
  :Ähnliche Bücher anzeigen;
}

partition Benutzer {
  if (Ähnliche Buch wählen?) then (ja)
    :Buch aus Ähnliche Bücher auswählen;
    -> [Buchdetails] 
    back to :Buchdetails anzeigen;
  else (nein)
    :Klick auf "Write Review";
    if (Rezension schreiben?) then (ja)
      :Rezension eingeben;
    else (nein)
      :Zurück zur Trefferliste;
      detach
    endif
  endif
}

partition System {
  if (Bewertung gültig?) then (ja)
    :Rezension speichern;
  else (nein)
    :Fehlermeldung anzeigen;
  endif
}

partition Benutzer {
  :Anwendung beenden;
  stop
}

@enduml