@startuml Buchverwaltungssystem_Sequenzdiagramm

' Akteure und Objekte definieren
actor Benutzer
participant "Benutzeroberfläche" as UI
participant "Katalog" as Katalog
participant "Suchanfrage" as Suchanfrage
participant "Buch" as Buch
participant "Autor" as Autor
participant "Genre" as Genre
participant "Rezensionen" as Rezensionen
participant "Verlag" as Verlag
participant "Tag" as Tag

title Buchverwaltungssystem - Sequenzdiagramm für Buchsuche, Detailanzeige, SimilarBooks und About-Button

' Sequenz 0: About anzeigen
group About anzeigen
    Benutzer -> UI: klickt "About"
    activate UI
    
    UI -> UI: öffne AboutPanel
    UI --> Benutzer: zeige Informationen über Litera
    deactivate UI
end

' Sequenz 1: Buchsuche
group Buchsuche
    Benutzer -> UI: Suchparameter eingeben (Titel, Autor, Genre)
    activate UI
    
    UI -> Suchanfrage: erstellen(titel, autor, genre)
    activate Suchanfrage
    
    UI -> Katalog: suche(suchanfrage)
    activate Katalog
    
    Katalog -> Buch: filtereNachKriterien(titel, autor, genre)
    activate Buch
    
    Buch --> Katalog: gefilterte Buchliste
    deactivate Buch
    
    Katalog --> UI: Suchergebnisse
    deactivate Katalog
    
    UI --> Benutzer: Zeige Suchergebnisse an
    deactivate UI
end

' Sequenz 2: Buchdetails anzeigen
group Buchdetails anzeigen
    Benutzer -> UI: Buch auswählen
    activate UI
    
    UI -> Katalog: zeigeDetails(buch)
    activate Katalog
    
    Katalog -> Buch: getDetails()
    activate Buch
    
    Buch -> Autor: getDetails()
    activate Autor
    Autor --> Buch: Autordetails
    deactivate Autor
    
    Buch -> Genre: getDetails()
    activate Genre
    Genre --> Buch: Genredetails
    deactivate Genre
    
    Buch -> Verlag: getDetails()
    activate Verlag
    Verlag --> Buch: Verlagdetails
    deactivate Verlag
    
    Buch -> Rezensionen: getAll()
    activate Rezensionen
    Rezensionen --> Buch: Liste aller Rezensionen
    deactivate Rezensionen
    
    Buch -> Tag: getAll()
    activate Tag
    Tag --> Buch: Liste aller Tags
    deactivate Tag
    
    Buch --> Katalog: Vollständige Buchdetails
    deactivate Buch
    
    Katalog --> UI: Buchdetails
    deactivate Katalog
    
    UI --> Benutzer: Zeige Buchdetails an
    deactivate UI

    ' Neuer Schritt: Ähnliche Bücher laden
    UI -> Katalog: holeÄhnlicheBuecher(buchId)
    activate Katalog
    
    Katalog -> Buch: filtereNachGemeinsamenGenres(buch, MIN_MATCHING_GENRES)
    activate Buch
    Buch --> Katalog: Liste ähnlicher Bücher
    deactivate Buch
    
    Katalog --> UI: gebe Liste ähnlicher Bücher zurück
    deactivate Katalog
    
    UI --> Benutzer: zeige SimilarBooks-Panel mit Thumbnails und Titeln
end

' Sequenz 3: Rezension hinzufügen
group Rezension hinzufügen
    Benutzer -> UI: Rezension eingeben (Text, Bewertung)
    activate UI
    
    UI -> Rezensionen: erstellen(text, bewertung, datum, buch)
    activate Rezensionen
    
    Rezensionen -> Buch: addRezension(rezension)
    activate Buch
    Buch --> Rezensionen: Bestätigung
    deactivate Buch
    
    Rezensionen --> UI: Bestätigung
    deactivate Rezensionen
    
    UI --> Benutzer: Bestätigung anzeigen
    deactivate UI
end

@enduml